### ISSUE TITLE
ld:cannot find -lGLESv2

### ISSUE THREAD

**Issue by RuleNumber1** [henrihallik/qt-cross-compile-pi5_aarch64#1]
1.my raspi4b bullseye 64bit desktop has no opt/vc, although i still pass the make -j24&&make install
2.while i use my qmake 5.15.8,i got compile error:
ld:cannot find -lGLESv2
ld:cannot find -lEGL
ld:cannot find -lpthread
ld:cannot find -lm
i`m looking for methods to solve this problem plz

**Comment by henrihallik** [comment]
the opt/vc is optional, its fine if u dont have it. these are linker errors, its either u dont have these libraries installed on your raspberry pi or they are not properly linked in your .pro or cmake QT project file.  try:
sudo apt install libgles2-mesa-dev
sudo apt install libegl1-mesa-dev
sudo apt install libpthread-stubs0-dev
sudo apt install libm-dev

u need to run piece of the code that copies the sysroot to your dev pc after installing new stuff to your RPI.

# variables
raspberry_ip="pi5.local"
raspberry_user="pi"
raspberry_pwd="pi"

# rsync files from raspberry
cecho "YELLOW" "Syncing files from raspberry pi."
touch ~/.ssh/known_hosts
ssh-keyscan $raspberry_ip >> ~/.ssh/known_hosts
sshpass -p "$raspberry_pwd" rsync -avz --rsync-path="sudo rsync" --delete "$raspberry_user"@"$raspberry_ip":/lib ~/rpi-qt/sysroot
sshpass -p "$raspberry_pwd" rsync -avz --rsync-path="sudo rsync" --delete "$raspberry_user"@"$raspberry_ip":/usr/include ~/rpi-qt/sysroot/usr
sshpass -p "$raspberry_pwd" rsync -avz --rsync-path="sudo rsync" --delete "$raspberry_user"@"$raspberry_ip":/usr/lib ~/rpi-qt/sysroot/usr
sshpass -p "$raspberry_pwd" rsync -avz --rsync-path="sudo rsync" --delete "$raspberry_user"@"$raspberry_ip":/opt/vc ~/rpi-qt/sysroot/opt
sshpass -p "$raspberry_pwd" rsync -avz --rsync-path="sudo rsync" --delete "$raspberry_user"@"$raspberry_ip":/usr/local/include ~/rpi-qt/sysroot/usr/local
sshpass -p "$raspberry_pwd" rsync -avz --rsync-path="sudo rsync" --delete "$raspberry_user"@"$raspberry_ip":/usr/local/lib ~/rpi-qt/sysroot/usr/local
sshpass -p "$raspberry_pwd" rsync -avz --rsync-path="sudo rsync" --delete "$raspberry_user"@"$raspberry_ip":/etc/alternatives ~/rpi-qt/sysroot/etc
cecho "GREEN" "Files synced from raspberry pi."

# Fix symbolic links
cecho "YELLOW" "Fix symbolic links."
if [ ! -f ~/rpi-qt/sysroot-relativelinks.py ]
then
    wget -P ~/rpi-qt https://raw.githubusercontent.com/abhiTronix/rpi_rootfs/master/scripts/sysroot-relativelinks.py
    sudo chmod +x ~/rpi-qt/sysroot-relativelinks.py
fi
~/rpi-qt/sysroot-relativelinks.py ~/rpi-qt/sysroot
cecho "GREEN" "Symbolic links fixed."

in my .pro file i have had to add full path to the libraries folder that are synced to my dev pc. like this 
LIBS += -L/root/rpi-qt/sysroot/usr/lib/aarch64-linux-gnu/
to fix the linker issues.

**Comment by RuleNumber1** [comment]
yeah,i got this try and solve the problem, thank u very much!
but this shell still exists some bug, such as gstreamer1.0-doc can not be installed and some other bugs,but totally it`s not fatal error,i have already working my qt ui on raspbian bullseye 64-bit, thank u very much again!
